/* Generated by Thoáng Menu Editor */
window.THOANG_MENU = [
  {
    "id": "signature-cocktail",
    "categoryVi": "Cocktail",
    "categoryEn": "Cocktails",
    "nameVi": "Signature Cocktail",
    "nameEn": "Signature Cocktail",
    "descriptionVi": "Một lựa chọn đặc trưng được pha tại quầy bar của Thoáng.",
    "descriptionEn": "A signature creation mixed at the Thoáng bar.",
    "price": "Liên hệ",
    "image": "assets/cocktail-3.jpg",
    "available": true
  },
  {
    "id": "light-cocktail",
    "categoryVi": "Cocktail",
    "categoryEn": "Cocktails",
    "nameVi": "Nhẹ & Tinh Tế",
    "nameEn": "Light & Elegant",
    "descriptionVi": "Hương vị nhẹ nhàng cho một buổi tối thư thái.",
    "descriptionEn": "A lighter choice for a relaxed evening.",
    "price": "Liên hệ",
    "image": "assets/cocktail-2.jpg",
    "available": true
  }
];
